---
apiVersion: v1
kind: Pod
metadata:
  name: yg-airflow-test
spec:
  containers:
    - args: []
      command: []
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: database_url
        - name: AIRFLOW__LOGGING__REMOTE_LOGGING
          valueFrom:
            configMapKeyRef:
              name: airflow-remote-logging-config
              key: remote_logging_enabled
        - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
          valueFrom:
            configMapKeyRef:
              name: airflow-remote-logging-config
              key: conn_id
        - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
          valueFrom:
            configMapKeyRef:
              name: airflow-remote-logging-config
              key: remote_base_log_folder
        - name: AIRFLOW_CONN_AWS_DEFAULT
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: aws_conn_uri
      envFrom: []
      image: hahafree12/dwfs-airflow:latest
      imagePullPolicy: IfNotPresent
      name: base
      ports: []
      volumeMounts:
        - mountPath: "/airflow/logs"
          name: airflow-logs
        - mountPath: /dags
          name: airflow-dags
          readOnly: true
  hostNetwork: false
  restartPolicy: Never
  nodeSelector:
    {}
  affinity:
    {}
  tolerations:
    []
  volumes:
    - name: airflow-dags
      persistentVolumeClaim:
        claimName: airflow-dags
    - name: airflow-logs
      persistentVolumeClaim:
        claimName: airflow-logs