apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  database_url: {{ .Values.database_url | b64enc }}
  aws_conn_uri: {{ .Values.airflow_config.remote_logging.conn_id_uri | b64enc }}